### PR TITLE
Code Refactor, Package Updates, New Tests

### PR DESCRIPTION
**Pull request by LucasMoffitt**
- Updating Azure DocumentDB client to 1.7
- General Code Cleanup / Refactor
- Abstracted out the Test Base to allow for more structured tests
- Queries now take into account collection name (i.e FindAsync)
- UserStore now updates custom user type properties when calling UpdateAsync
- Added tests to cover UserStore custom user type updates

### CODE REVIEW

**Comment by tracker086** [comment]
Thank you for the contribution!

**Comment by LucasMoffitt** [comment]
Great! Thanks!

Any chance of a nuget package update please?

**Comment by tracker086** [comment]
Yes, I'll update it ASAP!

**Comment by LucasMoffitt** [comment]
Hey! Any update on the package update?

Thanks

Lucas

**Comment by tracker086** [comment]
Sorry, busy days :)
Package updated. Let me know if I can do something for you.
Thanks!

**Pull request merged**
